export const ROLES = {
  ADMIN: "admin",
  DOCTOR: "doctor",
  NURSE: "nurse",
  RECEPTIONIST: "receptionist",
  LAB_TECH: "lab_tech",
  PHARMACIST: "pharmacist",
};

export const STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
};

export const APPOINTMENT_STATUS = {
  SCHEDULED: "scheduled",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  NO_SHOW: "no_show",
};

export const MEDICAL_RECORD_TYPES = {
  DIAGNOSIS: "diagnosis",
  PRESCRIPTION: "prescription",
  LAB_RESULT: "lab_result",
  PROGRESS_NOTE: "progress_note",
};

// Centralized permission definitions
export const PERMISSIONS = {
  VIEW_PATIENTS: "view_patients",
  EDIT_PATIENTS: "edit_patients",
  VIEW_MEDICAL_RECORDS: "view_medical_records",
  EDIT_MEDICAL_RECORDS: "edit_medical_records",
  PRESCRIBE: "prescribe",
  VIEW_APPOINTMENTS: "view_appointments",
  MANAGE_APPOINTMENTS: "manage_appointments",
  EDIT_LAB_RESULTS: "edit_lab_results",
  VIEW_PRESCRIPTIONS: "view_prescriptions",
  DISPENSE_MEDICATION: "dispense_medication",
  ALL: "all",
};

// Role-permission mapping
export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [PERMISSIONS.ALL],
  [ROLES.DOCTOR]: [
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.EDIT_PATIENTS,
    PERMISSIONS.VIEW_MEDICAL_RECORDS,
    PERMISSIONS.EDIT_MEDICAL_RECORDS,
    PERMISSIONS.PRESCRIBE,
    PERMISSIONS.VIEW_APPOINTMENTS,
    PERMISSIONS.MANAGE_APPOINTMENTS,
  ],
  [ROLES.NURSE]: [
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.EDIT_PATIENTS,
    PERMISSIONS.VIEW_MEDICAL_RECORDS,
    PERMISSIONS.EDIT_MEDICAL_RECORDS,
    PERMISSIONS.VIEW_APPOINTMENTS,
  ],
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.EDIT_PATIENTS,
    PERMISSIONS.VIEW_APPOINTMENTS,
    PERMISSIONS.MANAGE_APPOINTMENTS,
  ],
  [ROLES.LAB_TECH]: [
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.VIEW_MEDICAL_RECORDS,
    PERMISSIONS.EDIT_LAB_RESULTS,
  ],
  [ROLES.PHARMACIST]: [
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.VIEW_PRESCRIPTIONS,
    PERMISSIONS.DISPENSE_MEDICATION,
  ],
};

export default {
  ROLES,
  STATUS,
  APPOINTMENT_STATUS,
  MEDICAL_RECORD_TYPES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
};
